/**
 * The HUD, the panels, the boards and the signs.
 *
 * Data only. This file imports nothing and is imported by strings.ts, which is
 * what keeps the two from forming a cycle and what makes this file safe to
 * hand to a translator: there is nothing in it to break.
 *
 * On the Spanish, German and French: translated for character rather than word
 * for word, and cut to fit. Every panel in the HUD is a fixed pixel width, and
 * German in particular runs long, so several lines here are shorter than a
 * faithful rendering would be. A line that overruns its box is not drawn
 * smaller, it is drawn over the thing next to it.
 *
 * Golf keeps its English vocabulary wherever golfers in that language use it:
 * par, birdie, putt, green. Substituting a native word for those reads as a
 * translation of a golf game rather than as a golf game.
 */

export const UI: Record<string, Record<string, string>> = {
  en: {
    // ---- the strip along the top -------------------------------------------
    "hud.practice": "PRACTICE",
    "hud.secret": "SECRET",
    "hud.shot": "Shot {n}",
    "hud.shotOf": "Shot {n} of {max}  ·  {dist}",
    "hud.holed": "{n} holed  ·  shot {shot}",
    "hud.toJoin": "to join",
    "hud.toJoinKey": "E  to join",
    "hud.boardAway": "Board {dist}",
    "hud.par": "PAR {n}",
    // ---- the scorecard and the standings -----------------------------------
    "hud.total": "TOT",
    "hud.parLine": "Par {par}    {toPar}",
    "hud.playing": "PLAYING  {n}",
    "hud.roundComplete": "ROUND COMPLETE    {total}  ({toPar})",
    "hud.playAgain": "to play the course again",
    "hud.playAgainKey": "Press E to play the course again",
    // ---- the chips ---------------------------------------------------------
    "hud.colada": "COLADA",
    "hud.dig": "DIG",
    "hud.digKey": "DIG  (E)",
    "hud.sweeping": "SWEEPING",
    "hud.nothingFound": "NOTHING",
    // ---- what to press -----------------------------------------------------
    "prompt.walkToBall": "Walk up to your ball",
    "prompt.address": "{E}  to address the ball",
    "prompt.addressKey": "Press  E  to address the ball",
    "prompt.aim": "Look where you want it to go,  then  {E}",
    "prompt.aimKey": "Look where you want it to go,  then  E",
    // ---- the swing meter ---------------------------------------------------
    "meter.setPower": "SET POWER",
    "meter.hitLine": "HIT THE LINE",
    "meter.lockPower": "to lock the power",
    "meter.lockPowerKey": "Press  E  to lock the power",
    "meter.onLine": "on the white line",
    "meter.onLineAgain": "again on the white line",
    "meter.onLineKey": "Press  E  on the white line",
    "meter.crossCancels": "the cross cancels",
    "meter.crossCancelsShort": "cross cancels",
    "meter.fCancels": "F  cancel",
    // ---- the hub -----------------------------------------------------------
    "hub.title": "HUB",
    "hub.reset": "RESET",
    "hub.leave": "LEAVE",
    "hub.sure": "SURE?",
    "hub.close": "X",
    "hub.quests": "QUESTS",
    "hub.gear": "GEAR",
    "hub.stash": "STASH",
    "hub.settings": "SETTINGS",
    "hub.active": "ACTIVE",
    "hub.available": "AVAILABLE",
    "hub.completed": "COMPLETED",
    "hub.clubs": "CLUBS",
    "hub.balls": "BALLS",
    "hub.gearHint":
      "Tap an owned club or ball to hold it. Salt sells the rest, at the crate in the shack.",
    "hub.stashHint": "What you are carrying. Hand it in to the person who wants it.",
    "hub.settingsHint": "How the game looks to you. Nobody else is affected.",
    "hub.andMore": "and {n} more",
    "hub.nothingActive": "Nothing on the go. Have a word with somebody.",
    "hub.nothingAvailable": "Nothing on offer. Finish what you have started.",
    "hub.nothingDone": "Nothing finished yet.",
    "hub.speakTo": "Speak to {who}",
    "hub.readyToHandIn": "Completed. Speak to {who}",
    "hub.reward": "+{n} {pp}",
    "hub.progress": "{done} / {target}",
    // ---- settings ----------------------------------------------------------
    "settings.on": "ON",
    "settings.off": "OFF",
    "settings.hidePrompts": "Hide prompts",
    "settings.hidePromptsDetail":
      "Turns off the line at the bottom of the screen telling you what to do next.",
    "settings.talkInRounds": "Talk during rounds",
    "settings.talkInRoundsDetail":
      "Lets the characters stop you for a word mid-round. Never during a shot.",
    "settings.language": "Language",
    "settings.languageDetail": "Anything not translated yet stays in English.",
    // ---- the stash ---------------------------------------------------------
    "stash.shells": "Shells",
    "stash.shellsDetail": "{who} wants them, down on the south beach.",
    "stash.coconuts": "Coconuts",
    "stash.coconutsDetail": "{who} wants them, up by the palms.",
    "stash.scrap": "Scrap",
    "stash.scrapDetail": "Dug up with the detector. {who} can use it.",
    "stash.limitReached": "{n}  ·  limit reached today",
    // ---- the crate and the gear rows ---------------------------------------
    "shop.equipped": "EQUIPPED",
    "shop.equip": "EQUIP",
    "shop.atSalt": "{price}  ·  SALT",
    "shop.questReward": "Quest reward",
    "shop.questLocked": "Quest: {name}",
    "shop.walkAway": "Walk away to close",
    "shop.needLevel": "Level {n}",
    // ---- levelling ---------------------------------------------------------
    "level.title": "LEVEL {n}",
    "level.titleGained": "LEVEL {n}  (+{gained})",
    "level.onTheShelf": "{rank}  ·  {n} on the shelf",
    "level.connectWallet": "Connect a wallet to be paid for these",
    // ---- the four lines every quest conversation uses ----------------------
    "quest.take": "I will take it",
    "quest.notNow": "Not just now",
    "quest.collect": "Collect {n} {pp}",
    "quest.inAMinute": "In a minute",
    "quest.rightYouAre": "Right you are",
    // ---- the sign-up board out on the decking ------------------------------
    "sign.title": "PIRATE MINI GOLF",
    "sign.join": "Join the round",
    "sign.toJoin": "to join",
    "sign.toJoinKey": "Press E to join",
    "sign.playing": "{n} playing",
    "sign.watching": "{n} nearby",
    "sign.youAreIn": "You are in. Walk to the tee.",
    // ---- the leaderboard sign ----------------------------------------------
    "board.waiting": "Waiting for the ledger…",
    "board.nobody": "Nobody yet. Be the first.",
    // ---- the quest sign ----------------------------------------------------
    "questboard.title": "QUESTS",
    "questboard.nothing": "Nothing on. Ask around.",
    "questboard.readyToHandIn": "Completed. Speak to {who}",
    // ---- the ranks, keyed off the English name in ranks.ts -----------------
    "rank.cabin-boy": "Cabin Boy",
    "rank.deckhand": "Deckhand",
    "rank.buccaneer": "Buccaneer",
    "rank.first-mate": "First Mate",
    "rank.captain": "Captain",
    "rank.pirate-lord": "Pirate Lord",
    // ---- the holes, keyed off the English name in course.ts ----------------
    "hole.the-jetty": "The Jetty",
    "hole.anchors-rest": "Anchor's Rest",
    "hole.triple-bridge": "Triple Bridge",
    "hole.the-blockade": "The Blockade",
    "hole.barrel-run": "Barrel Run",
    "hole.the-lighthouse": "The Lighthouse",
    "hole.ships-passing": "Ship's Passing",
    "hole.dead-mans-arch": "Dead Man's Arch",
    "hole.treasure-run": "Treasure Run",
    "hole.the-secret-hole": "The Secret Hole",
    // ---- what each hole asks of you ----------------------------------------
    "holeHint.the-jetty": "A gentle dog-leg. Play it off the rail.",
    "holeHint.anchors-rest": "Up the ramp, past the anchor. Give it some legs.",
    "holeHint.triple-bridge": "Down the slope, then thread the gaps.",
    "holeHint.the-blockade": "Two open trenches between you and the pin.",
    "holeHint.barrel-run": "Time the barrel, then stay dry.",
    "holeHint.the-lighthouse": "Around the light, then up onto the deck.",
    "holeHint.ships-passing": "The galleon ferries you across. Wait for your gap.",
    "holeHint.dead-mans-arch": "Two big rollers. Hit it firm or the hill sends it back.",
    "holeHint.treasure-run": "The whole island, two swinging bridges, and a chest at the end.",
    "holeHint.the-secret-hole":
      "Nobody has to play this. Twenty shots, then it takes the ball off you.",
    "holeHint.practice": "Warm up. Hole it and the ball comes straight back.",
    // ---- the leaderboard sign, keyed off its page keys in config -----
    "board.levelHeading": "TOP RANKS",
    "board.levelNote": "By lifetime Pixel Points",
    "board.bestHeading": "BEST ROUNDS",
    "board.bestNote": "Fewest strokes for the nine",
    "board.todayHeading": "TODAY",
    "board.todayNote": "Pixel Points earned today",
    // ---- the shop catalogue, keyed off the English name in shop.ts ---
    "item.stick-club": "Stick Club",
    "itemBlurb.stick-club": "A stick. You found it on the way in.",
    "item.standard-club": "Standard Club",
    "itemBlurb.standard-club": "An actual putter, for an actual deckhand.",
    "item.golden-club": "Golden Club",
    "itemBlurb.golden-club": "Heavier than gold has any business being.",
    "item.ruby-club": "Ruby Club",
    "itemBlurb.ruby-club": "Set with a stone nobody asks about twice.",
    "item.master-club": "Master Club",
    "itemBlurb.master-club": "Carried by people who no longer need to prove it.",
    "item.pirate-cutlass": "Pirate Cutlass",
    "itemBlurb.pirate-cutlass": "Not a golf club. Nobody is going to tell you that.",
    "item.flag-club": "Flag Club",
    "itemBlurb.flag-club": "Three in one round. They took the pin down for you.",
    "item.mechanical-club": "Mechanical Club",
    "itemBlurb.mechanical-club": "Clicks when you line it up. Sally knows exactly why.",
    "item.seaside-club": "Seaside Club",
    "itemBlurb.seaside-club": "Ten shells off the beach, handed over in person.",
    "item.neon-club": "Neon Club",
    "itemBlurb.neon-club": "Lit up like the pier on a Saturday.",
    "item.stone-ball": "Stone Ball",
    "itemBlurb.stone-ball": "Rolls. Barely.",
    "item.standard-ball": "Standard Ball",
    "itemBlurb.standard-ball": "The first real ball you will own.",
    "item.golden-ball": "Golden Ball",
    "itemBlurb.golden-ball": "No advantage whatsoever. Everyone can see it.",
    "item.ruby-ball": "Ruby Ball",
    "itemBlurb.ruby-ball": "Catches the light on the way past the pin.",
    "item.master-ball": "Master Ball",
    "itemBlurb.master-ball": "Thirty levels of not giving up.",
    "item.crown-ball": "Crown Ball",
    "itemBlurb.crown-ball": "There is one rank above Captain, and you hold it.",
    "item.8-ball": "8 Ball",
    "itemBlurb.8-ball": "Eight on every hole. Deliberately.",
    "item.cannon-ball": "Cannon Ball",
    "itemBlurb.cannon-ball": "Ran out of shots on all nine. Some kind of record.",
    "item.coconut-ball": "Coconut Ball",
    "itemBlurb.coconut-ball": "Off one of the palms. Still has the husk on.",
    "item.neon-ball": "Neon Ball",
    "itemBlurb.neon-ball": "You will not lose this one after dark.",
    // ---- odds and ends -----------------------------------------------
    "board.levelShort": "Lv {n}",
    // ---- the callouts the game raises for itself --------------------
    "toast.welcome.title": "Pirate Mini Golf",
    "toast.welcome.detail": "Have a putt on the practice green. Join a round at the board when you are ready.",
    "toast.tenthShut.title": "The tenth is shut",
    "toast.tenthShut.detail": "Level {n} opens it. Salt knows more than he lets on.",
    "toast.holeTitle": "Hole {n} — {name}",
    "toast.holeDetail": "Par {par}. {hint}",
    "toast.holeWithOne": "Par {par}. Playing with {n} other.",
    "toast.holeWithOthers": "Par {par}. Playing with {n} others.",
    "toast.roundLeft.title": "Round left",
    "toast.roundLeft.detail": "Card torn up and nothing scored. The board by the first tee signs you back on.",
    "toast.cardCleared.title": "Card cleared",
    "toast.cardCleared.detail": "Every hole back to unplayed.",
    "toast.detectorOut": "Detector out",
    "toast.detectorAway": "Detector away",
    "toast.sweepSlowly": "Sweep slowly.",
    "toast.clubOut": "Club out",
    "toast.clubAway": "Club away",
    "toast.scrap.title": "Scrap",
    "toast.scrap.detail": "Something metal, and older than you.",
    "toast.cancelled.title": "Swing cancelled",
    "toast.cancelled.detail": "No stroke counted. Line it up again.",
    "toast.lostBall.title": "Lost ball",
    "toast.lostBall.detail": "+{n} stroke. Playing again from where it last came to rest.",
    "toast.ballReset.title": "Ball reset",
    "toast.ballReset.penalty": "Back to your last lie, +{n} stroke.",
    "toast.ballReset.free": "Back to your last lie, no penalty.",
    "toast.pickedUp.title": "Picked up",
    "toast.pickedUp.detail": "Maximum {n} strokes on {hole}.",
    "toast.inOne": "In one",
    "toast.holedSecret": "You holed the secret",
    "toast.holed": "Holed",
    "toast.secretOne": "{n} shot. Very few people see that.",
    "toast.secretMany": "{n} shots. Very few people see that.",
    "toast.practiceOne": "{n} shot. That's {total} down on the practice green.",
    "toast.practiceMany": "{n} shots. That's {total} down on the practice green.",
    "score.holeInOne": "HOLE IN ONE!",
    "score.eagle": "EAGLE",
    "score.birdie": "BIRDIE",
    "score.par": "PAR",
    "score.bogey": "BOGEY",
    "score.doubleBogey": "DOUBLE BOGEY",
    "score.over": "+{n}",
    "toast.holeResultOne": "{n} shot on hole {hole}. You're {standing}.",
    "toast.holeResultMany": "{n} shots on hole {hole}. You're {standing}.",
    "toast.roundDone.title": "Round complete",
    "toast.roundDone.detail": "{total} shots for the nine, {label} against a par of {par}.{place} Going again.",
    "toast.beat": "  Beat {n} of {of}.",
    "toast.cardIn.title": "Card in",
    "par.level": "level par",
    "par.over": "{n} over",
    "par.under": "{n} under",
    // ---- what somebody says when they take something off you ----------
    "hand.shellsOne": "{n} shell taken",
    "hand.shellsMany": "{n} shells taken",
    "hand.coconutsOne": "{n} coconut taken",
    "hand.coconutsMany": "{n} coconuts taken",
    "hand.paid": "+{n} {pp}",
    "hand.noWallet": "Connect a wallet to be paid for these",
    "hand.noMoreToday": "He will not take any more today",
    "hand.leftInHand": "{n} left in hand. He takes {limit} a day.",
    "hand.forJug": "{n} for the jug",
    "hand.thatIsTheJug": "That is the jug",
    "hand.jugWanted": "{n} more wanted.",
    "hand.jugWantedPaid": "{n} more wanted.  +{paid} {pp}",
    "hand.goTellHim": "Go and tell him.",
    "hand.motor.title": "The old motor",
    "hand.motor.detail": "Heavier than it looks. Coconutty will want to see this.",
    "hand.scrapOne": "{n} scrap handed over",
    "hand.scrapMany": "{n} scrap handed over",
    "hand.scrapDetail": "{total} in all. She is sorting it as you leave.",
    "hand.detectorOut": "Detector out",
    "hand.detectorAway": "Detector away",
    "hand.sweepSlowly": "Sweep slowly and let it click.",
    "hand.notThisTime": "Not this time"
  },
  es: {
    // ---- the strip along the top -------------------------------------------
    "hud.practice": "PRÁCTICA",
    "hud.secret": "SECRETO",
    "hud.shot": "Golpe {n}",
    "hud.shotOf": "Golpe {n} de {max}  ·  {dist}",
    "hud.holed": "{n} metidas  ·  golpe {shot}",
    "hud.toJoin": "unirte",
    "hud.toJoinKey": "E  unirte",
    "hud.boardAway": "Tablón {dist}",
    "hud.par": "PAR {n}",
    // ---- the scorecard and the standings -----------------------------------
    "hud.total": "TOT",
    "hud.parLine": "Par {par}    {toPar}",
    "hud.playing": "JUGANDO  {n}",
    "hud.roundComplete": "VUELTA TERMINADA    {total}  ({toPar})",
    "hud.playAgain": "para jugar otra vuelta",
    "hud.playAgainKey": "Pulsa E para jugar otra vuelta",
    // ---- the chips ---------------------------------------------------------
    "hud.colada": "COLADA",
    "hud.dig": "CAVA",
    "hud.digKey": "CAVA  (E)",
    "hud.sweeping": "BUSCANDO",
    "hud.nothingFound": "NADA",
    // ---- what to press -----------------------------------------------------
    "prompt.walkToBall": "Acércate a tu bola",
    "prompt.address": "{E}  para colocarte",
    "prompt.addressKey": "Pulsa  E  para colocarte",
    "prompt.aim": "Mira adonde quieres mandarla,  y  {E}",
    "prompt.aimKey": "Mira adonde quieres mandarla,  y luego  E",
    // ---- the swing meter ---------------------------------------------------
    "meter.setPower": "FIJA LA FUERZA",
    "meter.hitLine": "DALE A LA LÍNEA",
    "meter.lockPower": "para fijar la fuerza",
    "meter.lockPowerKey": "Pulsa  E  para fijar la fuerza",
    "meter.onLine": "en la línea blanca",
    "meter.onLineAgain": "otra vez en la línea blanca",
    "meter.onLineKey": "Pulsa  E  en la línea blanca",
    "meter.crossCancels": "la cruz cancela",
    "meter.crossCancelsShort": "la cruz cancela",
    "meter.fCancels": "F  cancelar",
    // ---- the hub -----------------------------------------------------------
    "hub.title": "MOCHILA",
    "hub.reset": "REPETIR",
    "hub.leave": "SALIR",
    "hub.sure": "¿SEGURO?",
    "hub.close": "X",
    "hub.quests": "MISIONES",
    "hub.gear": "EQUIPO",
    "hub.stash": "ALIJO",
    "hub.settings": "AJUSTES",
    "hub.active": "ACTIVAS",
    "hub.available": "LIBRES",
    "hub.completed": "HECHAS",
    "hub.clubs": "PALOS",
    "hub.balls": "BOLAS",
    "hub.gearHint":
      "Toca un palo o bola que ya tengas para usarlo. Lo demás lo vende Salt, en la cabaña.",
    "hub.stashHint": "Lo que llevas encima. Entrégalo a quien lo esté esperando.",
    "hub.settingsHint": "Cómo ves tú el juego. A nadie más le afecta.",
    "hub.andMore": "y {n} más",
    "hub.nothingActive": "Nada entre manos. Habla con alguien.",
    "hub.nothingAvailable": "Nada que coger. Termina lo que ya has empezado.",
    "hub.nothingDone": "Nada terminado todavía.",
    "hub.speakTo": "Habla con {who}",
    "hub.readyToHandIn": "Hecha. Habla con {who}",
    "hub.reward": "+{n} {pp}",
    "hub.progress": "{done} / {target}",
    // ---- settings ----------------------------------------------------------
    "settings.on": "SÍ",
    "settings.off": "NO",
    "settings.hidePrompts": "Ocultar avisos",
    "settings.hidePromptsDetail": "Quita la línea de abajo que te va diciendo qué hacer.",
    "settings.talkInRounds": "Hablar durante la vuelta",
    "settings.talkInRoundsDetail":
      "Deja que te paren a charlar durante la vuelta. Nunca en mitad de un golpe.",
    "settings.language": "Idioma",
    "settings.languageDetail": "Lo que todavía no está traducido se queda en inglés.",
    // ---- the stash ---------------------------------------------------------
    "stash.shells": "Conchas",
    "stash.shellsDetail": "{who} las quiere, abajo en la playa sur.",
    "stash.coconuts": "Cocos",
    "stash.coconutsDetail": "{who} los quiere, arriba junto a las palmeras.",
    "stash.scrap": "Chatarra",
    "stash.scrapDetail": "Se desentierra con el detector. A {who} le sirve.",
    "stash.limitReached": "{n}  ·  hoy ya no acepta más",
    // ---- the crate and the gear rows ---------------------------------------
    "shop.equipped": "EN MANO",
    "shop.equip": "USAR",
    "shop.atSalt": "{price}  ·  SALT",
    "shop.questReward": "Recompensa de misión",
    "shop.questLocked": "Misión: {name}",
    "shop.walkAway": "Aléjate para cerrar",
    "shop.needLevel": "Nivel {n}",
    // ---- levelling ---------------------------------------------------------
    "level.title": "NIVEL {n}",
    "level.titleGained": "NIVEL {n}  (+{gained})",
    "level.onTheShelf": "{rank}  ·  {n} en el estante",
    "level.connectWallet": "Conecta una cartera para cobrar por esto",
    // ---- the four lines every quest conversation uses ----------------------
    "quest.take": "Me la quedo",
    "quest.notNow": "Ahora no",
    "quest.collect": "Cobrar {n} {pp}",
    "quest.inAMinute": "En un rato",
    "quest.rightYouAre": "Muy bien",
    // ---- the sign-up board out on the decking ------------------------------
    "sign.title": "PIRATE MINI GOLF",
    "sign.join": "Únete a la vuelta",
    "sign.toJoin": "para unirte",
    "sign.toJoinKey": "Pulsa E para unirte",
    "sign.playing": "{n} jugando",
    "sign.watching": "{n} cerca",
    "sign.youAreIn": "Estás dentro. Ve al tee.",
    // ---- the leaderboard sign ----------------------------------------------
    "board.waiting": "Esperando al registro…",
    "board.nobody": "Nadie todavía. Sé el primero.",
    // ---- the quest sign ----------------------------------------------------
    "questboard.title": "MISIONES",
    "questboard.nothing": "Nada en marcha. Pregunta por ahí.",
    "questboard.readyToHandIn": "Hecha. Habla con {who}",
    // ---- the ranks, keyed off the English name in ranks.ts -----------------
    "rank.cabin-boy": "Grumete",
    "rank.deckhand": "Marinero",
    "rank.buccaneer": "Bucanero",
    "rank.first-mate": "Contramaestre",
    "rank.captain": "Capitán",
    "rank.pirate-lord": "Señor Pirata",
    // ---- the holes, keyed off the English name in course.ts ----------------
    "hole.the-jetty": "El Muelle",
    "hole.anchors-rest": "El Ancla",
    "hole.triple-bridge": "Puente Triple",
    "hole.the-blockade": "El Bloqueo",
    "hole.barrel-run": "Paso del Barril",
    "hole.the-lighthouse": "El Faro",
    "hole.ships-passing": "Paso del Barco",
    "hole.dead-mans-arch": "Arco del Muerto",
    "hole.treasure-run": "Ruta del Tesoro",
    "hole.the-secret-hole": "El Hoyo Secreto",
    // ---- what each hole asks of you ----------------------------------------
    "holeHint.the-jetty": "Un dogleg suave. Juégala contra la banda.",
    "holeHint.anchors-rest": "Por la rampa, pasado el ancla. Dale fuerte.",
    "holeHint.triple-bridge": "Cuesta abajo, y luego enhebra los huecos.",
    "holeHint.the-blockade": "Dos zanjas abiertas entre tú y la bandera.",
    "holeHint.barrel-run": "Calcula el barril, y no te mojes.",
    "holeHint.the-lighthouse": "Rodea el faro y sube a la plataforma.",
    "holeHint.ships-passing": "El galeón te cruza. Espera tu hueco.",
    "holeHint.dead-mans-arch": "Dos subidas largas. Dale firme o la cuesta te la devuelve.",
    "holeHint.treasure-run": "La isla entera, dos puentes colgantes y un cofre al final.",
    "holeHint.the-secret-hole": "Nadie tiene que jugar esto. Veinte golpes y te quita la bola.",
    "holeHint.practice": "Calentamiento. Métela y la bola vuelve sola.",
    // ---- the leaderboard sign, keyed off its page keys in config -----
    "board.levelHeading": "MEJOR RANGO",
    "board.levelNote": "Por Pixel Points de siempre",
    "board.bestHeading": "MEJORES VUELTAS",
    "board.bestNote": "Menos golpes en los nueve",
    "board.todayHeading": "HOY",
    "board.todayNote": "Pixel Points ganados hoy",
    // ---- the shop catalogue, keyed off the English name in shop.ts ---
    "item.stick-club": "Palo de Palo",
    "itemBlurb.stick-club": "Un palo. Lo encontraste al entrar.",
    "item.standard-club": "Palo Estándar",
    "itemBlurb.standard-club": "Un putter de verdad, para un marinero de verdad.",
    "item.golden-club": "Palo Dorado",
    "itemBlurb.golden-club": "Más pesado de lo que el oro tiene derecho a ser.",
    "item.ruby-club": "Palo Rubí",
    "itemBlurb.ruby-club": "Con una piedra por la que nadie pregunta dos veces.",
    "item.master-club": "Palo Maestro",
    "itemBlurb.master-club": "Lo llevan los que ya no necesitan demostrarlo.",
    "item.pirate-cutlass": "Sable Pirata",
    "itemBlurb.pirate-cutlass": "No es un palo de golf. Nadie te lo va a decir.",
    "item.flag-club": "Palo de la Bandera",
    "itemBlurb.flag-club": "Tres en una vuelta. Te quitaron la bandera del hoyo.",
    "item.mechanical-club": "Palo Mecánico",
    "itemBlurb.mechanical-club": "Hace clic al alinearlo. Sally sabe exactamente por qué.",
    "item.seaside-club": "Palo de la Orilla",
    "itemBlurb.seaside-club": "Diez conchas de la playa, entregadas en mano.",
    "item.neon-club": "Palo Neón",
    "itemBlurb.neon-club": "Encendido como el paseo marítimo un sábado.",
    "item.stone-ball": "Bola de Piedra",
    "itemBlurb.stone-ball": "Rueda. Apenas.",
    "item.standard-ball": "Bola Estándar",
    "itemBlurb.standard-ball": "La primera bola de verdad que vas a tener.",
    "item.golden-ball": "Bola Dorada",
    "itemBlurb.golden-ball": "Ninguna ventaja. Pero todo el mundo la ve.",
    "item.ruby-ball": "Bola Rubí",
    "itemBlurb.ruby-ball": "Coge la luz al pasar de largo la bandera.",
    "item.master-ball": "Bola Maestra",
    "itemBlurb.master-ball": "Treinta niveles de no rendirse.",
    "item.crown-ball": "Bola de la Corona",
    "itemBlurb.crown-ball": "Hay un rango por encima de Capitán, y es el tuyo.",
    "item.8-ball": "Bola 8",
    "itemBlurb.8-ball": "Ocho en cada hoyo. A propósito.",
    "item.cannon-ball": "Bala de Cañón",
    "itemBlurb.cannon-ball": "Sin golpes en los nueve. Algún tipo de récord.",
    "item.coconut-ball": "Bola de Coco",
    "itemBlurb.coconut-ball": "De una de las palmeras. Todavía con la cáscara.",
    "item.neon-ball": "Bola Neón",
    "itemBlurb.neon-ball": "Esta no la pierdes de noche.",
    // ---- odds and ends -----------------------------------------------
    "board.levelShort": "Nv {n}",
    // ---- the callouts the game raises for itself --------------------
    "toast.welcome.title": "Pirate Mini Golf",
    "toast.welcome.detail": "Da unos golpes en el green de prácticas. Apúntate en el tablón cuando quieras jugar.",
    "toast.tenthShut.title": "El décimo está cerrado",
    "toast.tenthShut.detail": "El nivel {n} lo abre. Salt sabe más de lo que aparenta.",
    "toast.holeTitle": "Hoyo {n} — {name}",
    "toast.holeDetail": "Par {par}. {hint}",
    "toast.holeWithOne": "Par {par}. Juegas con {n} más.",
    "toast.holeWithOthers": "Par {par}. Juegas con {n} más.",
    "toast.roundLeft.title": "Vuelta abandonada",
    "toast.roundLeft.detail": "Tarjeta rota y nada anotado. El tablón del primer tee te vuelve a apuntar.",
    "toast.cardCleared.title": "Tarjeta borrada",
    "toast.cardCleared.detail": "Todos los hoyos vuelven a sin jugar.",
    "toast.detectorOut": "Detector fuera",
    "toast.detectorAway": "Detector guardado",
    "toast.sweepSlowly": "Barre despacio.",
    "toast.clubOut": "Palo fuera",
    "toast.clubAway": "Palo guardado",
    "toast.scrap.title": "Chatarra",
    "toast.scrap.detail": "Algo de metal, y más viejo que tú.",
    "toast.cancelled.title": "Swing cancelado",
    "toast.cancelled.detail": "No cuenta el golpe. Vuelve a colocarte.",
    "toast.lostBall.title": "Bola perdida",
    "toast.lostBall.detail": "+{n} golpe. Se juega desde donde quedó parada la última vez.",
    "toast.ballReset.title": "Bola recolocada",
    "toast.ballReset.penalty": "Vuelves a tu última posición, +{n} golpe.",
    "toast.ballReset.free": "Vuelves a tu última posición, sin penalización.",
    "toast.pickedUp.title": "Recogida",
    "toast.pickedUp.detail": "Máximo {n} golpes en {hole}.",
    "toast.inOne": "De un golpe",
    "toast.holedSecret": "Metiste el secreto",
    "toast.holed": "Embocada",
    "toast.secretOne": "{n} golpe. Muy poca gente ve eso.",
    "toast.secretMany": "{n} golpes. Muy poca gente ve eso.",
    "toast.practiceOne": "{n} golpe. Ya llevas {total} en el green de prácticas.",
    "toast.practiceMany": "{n} golpes. Ya llevas {total} en el green de prácticas.",
    "score.holeInOne": "¡HOYO EN UNO!",
    "score.eagle": "EAGLE",
    "score.birdie": "BIRDIE",
    "score.par": "PAR",
    "score.bogey": "BOGEY",
    "score.doubleBogey": "DOBLE BOGEY",
    "score.over": "+{n}",
    "toast.holeResultOne": "{n} golpe en el hoyo {hole}. Vas {standing}.",
    "toast.holeResultMany": "{n} golpes en el hoyo {hole}. Vas {standing}.",
    "toast.roundDone.title": "Vuelta completa",
    "toast.roundDone.detail": "{total} golpes en los nueve, {label} sobre un par de {par}.{place} Otra vez.",
    "toast.beat": "  Superaste a {n} de {of}.",
    "toast.cardIn.title": "Tarjeta entregada",
    "par.level": "en el par",
    "par.over": "{n} sobre par",
    "par.under": "{n} bajo par",
    // ---- what somebody says when they take something off you ----------
    "hand.shellsOne": "{n} concha aceptada",
    "hand.shellsMany": "{n} conchas aceptadas",
    "hand.coconutsOne": "{n} coco aceptado",
    "hand.coconutsMany": "{n} cocos aceptados",
    "hand.paid": "+{n} {pp}",
    "hand.noWallet": "Conecta una cartera para cobrar por esto",
    "hand.noMoreToday": "Hoy ya no acepta más",
    "hand.leftInHand": "Te quedan {n} en la mano. Acepta {limit} al día.",
    "hand.forJug": "{n} para la jarra",
    "hand.thatIsTheJug": "Esa es la jarra",
    "hand.jugWanted": "Faltan {n}.",
    "hand.jugWantedPaid": "Faltan {n}.  +{paid} {pp}",
    "hand.goTellHim": "Ve a decírselo.",
    "hand.motor.title": "El motor viejo",
    "hand.motor.detail": "Más pesado de lo que parece. Coconutty va a querer verlo.",
    "hand.scrapOne": "{n} de chatarra entregada",
    "hand.scrapMany": "{n} de chatarra entregada",
    "hand.scrapDetail": "{total} en total. Ya la está separando mientras te vas.",
    "hand.detectorOut": "Detector fuera",
    "hand.detectorAway": "Detector guardado",
    "hand.sweepSlowly": "Barre despacio y deja que haga clic.",
    "hand.notThisTime": "Esta vez no"
  },
  de: {
    // ---- the strip along the top -------------------------------------------
    "hud.practice": "ÜBUNG",
    "hud.secret": "GEHEIM",
    "hud.shot": "Schlag {n}",
    "hud.shotOf": "Schlag {n} von {max}  ·  {dist}",
    "hud.holed": "{n} drin  ·  Schlag {shot}",
    "hud.toJoin": "mitspiel.",
    "hud.toJoinKey": "E  mitmachen",
    "hud.boardAway": "Tafel {dist}",
    "hud.par": "PAR {n}",
    // ---- the scorecard and the standings -----------------------------------
    "hud.total": "GES",
    "hud.parLine": "Par {par}    {toPar}",
    "hud.playing": "AM SPIELEN  {n}",
    "hud.roundComplete": "RUNDE BEENDET    {total}  ({toPar})",
    "hud.playAgain": "für eine neue Runde",
    "hud.playAgainKey": "E drücken für eine neue Runde",
    // ---- the chips ---------------------------------------------------------
    "hud.colada": "COLADA",
    "hud.dig": "GRABEN",
    "hud.digKey": "GRABEN  (E)",
    "hud.sweeping": "SUCHE",
    "hud.nothingFound": "NICHTS",
    // ---- what to press -----------------------------------------------------
    "prompt.walkToBall": "Geh zu deinem Ball",
    "prompt.address": "{E}  zum Ansprechen",
    "prompt.addressKey": "Drücke  E  zum Ansprechen",
    "prompt.aim": "Zielen, wohin sie soll,  dann  {E}",
    "prompt.aimKey": "Zielen, wohin sie soll,  dann  E",
    // ---- the swing meter ---------------------------------------------------
    "meter.setPower": "KRAFT WÄHLEN",
    "meter.hitLine": "LINIE TREFFEN",
    "meter.lockPower": "Kraft festlegen",
    "meter.lockPowerKey": "Drücke  E  für die Kraft",
    "meter.onLine": "auf der weißen Linie",
    "meter.onLineAgain": "wieder auf der weißen Linie",
    "meter.onLineKey": "Drücke  E  auf der weißen Linie",
    "meter.crossCancels": "das Kreuz bricht ab",
    "meter.crossCancelsShort": "Kreuz bricht ab",
    "meter.fCancels": "F  abbrechen",
    // ---- the hub -----------------------------------------------------------
    "hub.title": "RUCKSACK",
    "hub.reset": "NEU",
    "hub.leave": "GEHEN",
    "hub.sure": "SICHER?",
    "hub.close": "X",
    "hub.quests": "AUFTRÄGE",
    "hub.gear": "AUSRÜSTUNG",
    "hub.stash": "BEUTE",
    "hub.settings": "OPTIONEN",
    "hub.active": "LAUFEND",
    "hub.available": "OFFEN",
    "hub.completed": "ERLEDIGT",
    "hub.clubs": "SCHLÄGER",
    "hub.balls": "BÄLLE",
    "hub.gearHint":
      "Tippe auf einen Schläger oder Ball, den du hast. Den Rest verkauft Salt in der Hütte.",
    "hub.stashHint": "Was du bei dir hast. Bring es dem, der es haben will.",
    "hub.settingsHint": "Wie das Spiel für dich aussieht. Sonst niemanden.",
    "hub.andMore": "und {n} weitere",
    "hub.nothingActive": "Nichts am Laufen. Sprich mal jemanden an.",
    "hub.nothingAvailable": "Nichts im Angebot. Mach erst fertig, was läuft.",
    "hub.nothingDone": "Noch nichts fertig.",
    "hub.speakTo": "Sprich mit {who}",
    "hub.readyToHandIn": "Fertig. Sprich mit {who}",
    "hub.reward": "+{n} {pp}",
    "hub.progress": "{done} / {target}",
    // ---- settings ----------------------------------------------------------
    "settings.on": "AN",
    "settings.off": "AUS",
    "settings.hidePrompts": "Hinweise aus",
    "settings.hidePromptsDetail": "Schaltet die Zeile unten ab, die dir sagt, was zu tun ist.",
    "settings.talkInRounds": "Reden während der Runde",
    "settings.talkInRoundsDetail":
      "Die Figuren dürfen dich mitten in der Runde ansprechen. Nie beim Schlag.",
    "settings.language": "Sprache",
    "settings.languageDetail": "Was noch nicht übersetzt ist, bleibt englisch.",
    // ---- the stash ---------------------------------------------------------
    "stash.shells": "Muscheln",
    "stash.shellsDetail": "{who} will sie, unten am Südstrand.",
    "stash.coconuts": "Kokosnüsse",
    "stash.coconutsDetail": "{who} will sie, oben bei den Palmen.",
    "stash.scrap": "Schrott",
    "stash.scrapDetail": "Mit dem Detektor gefunden. {who} braucht es.",
    "stash.limitReached": "{n}  ·  heute nichts mehr",
    // ---- the crate and the gear rows ---------------------------------------
    "shop.equipped": "IN DER HAND",
    "shop.equip": "NEHMEN",
    "shop.atSalt": "{price}  ·  SALT",
    "shop.questReward": "Auftragslohn",
    "shop.questLocked": "Auftrag: {name}",
    "shop.walkAway": "Weggehen zum Schließen",
    "shop.needLevel": "Stufe {n}",
    // ---- levelling ---------------------------------------------------------
    "level.title": "STUFE {n}",
    "level.titleGained": "STUFE {n}  (+{gained})",
    "level.onTheShelf": "{rank}  ·  {n} im Regal",
    "level.connectWallet": "Wallet verbinden, um dafür bezahlt zu werden",
    // ---- the four lines every quest conversation uses ----------------------
    "quest.take": "Ich nehme ihn",
    "quest.notNow": "Gerade nicht",
    "quest.collect": "{n} {pp} abholen",
    "quest.inAMinute": "Gleich",
    "quest.rightYouAre": "Alles klar",
    // ---- the sign-up board out on the decking ------------------------------
    "sign.title": "PIRATE MINI GOLF",
    "sign.join": "Runde mitspielen",
    "sign.toJoin": "zum Mitspielen",
    "sign.toJoinKey": "E drücken zum Mitspielen",
    "sign.playing": "{n} spielen",
    "sign.watching": "{n} in der Nähe",
    "sign.youAreIn": "Du bist dabei. Geh zum Abschlag.",
    // ---- the leaderboard sign ----------------------------------------------
    "board.waiting": "Warte auf das Konto…",
    "board.nobody": "Noch niemand. Sei der Erste.",
    // ---- the quest sign ----------------------------------------------------
    "questboard.title": "AUFTRÄGE",
    "questboard.nothing": "Nichts los. Frag mal herum.",
    "questboard.readyToHandIn": "Fertig. Sprich mit {who}",
    // ---- the ranks, keyed off the English name in ranks.ts -----------------
    "rank.cabin-boy": "Schiffsjunge",
    "rank.deckhand": "Matrose",
    "rank.buccaneer": "Freibeuter",
    "rank.first-mate": "Maat",
    "rank.captain": "Kapitän",
    "rank.pirate-lord": "Piratenfürst",
    // ---- the holes, keyed off the English name in course.ts ----------------
    "hole.the-jetty": "Der Steg",
    "hole.anchors-rest": "Ankerplatz",
    "hole.triple-bridge": "Dreifachbrücke",
    "hole.the-blockade": "Die Sperre",
    "hole.barrel-run": "Fasslauf",
    "hole.the-lighthouse": "Der Leuchtturm",
    "hole.ships-passing": "Schiffspassage",
    "hole.dead-mans-arch": "Totenbogen",
    "hole.treasure-run": "Schatzlauf",
    "hole.the-secret-hole": "Das geheime Loch",
    // ---- what each hole asks of you ----------------------------------------
    "holeHint.the-jetty": "Ein sanftes Dogleg. Spiel sie über die Bande.",
    "holeHint.anchors-rest": "Die Rampe hoch, am Anker vorbei. Gib ihr Schwung.",
    "holeHint.triple-bridge": "Den Hang hinunter, dann durch die Lücken.",
    "holeHint.the-blockade": "Zwei offene Gräben zwischen dir und der Fahne.",
    "holeHint.barrel-run": "Timing beim Fass, dann trocken bleiben.",
    "holeHint.the-lighthouse": "Um das Licht herum, dann hoch aufs Deck.",
    "holeHint.ships-passing": "Die Galeone bringt dich hinüber. Warte auf die Lücke.",
    "holeHint.dead-mans-arch": "Zwei lange Wellen. Fest schlagen, sonst rollt sie zurück.",
    "holeHint.treasure-run": "Die ganze Insel, zwei Hängebrücken und am Ende eine Truhe.",
    "holeHint.the-secret-hole": "Das muss niemand spielen. Zwanzig Schläge, dann ist der Ball weg.",
    "holeHint.practice": "Aufwärmen. Versenke sie und der Ball kommt zurück.",
    // ---- the leaderboard sign, keyed off its page keys in config -----
    "board.levelHeading": "TOP-RÄNGE",
    "board.levelNote": "Nach Pixel Points insgesamt",
    "board.bestHeading": "BESTE RUNDEN",
    "board.bestNote": "Wenigste Schläge auf neun",
    "board.todayHeading": "HEUTE",
    "board.todayNote": "Heute verdiente Pixel Points",
    // ---- the shop catalogue, keyed off the English name in shop.ts ---
    "item.stick-club": "Stockschläger",
    "itemBlurb.stick-club": "Ein Stock. Du hast ihn auf dem Weg herein gefunden.",
    "item.standard-club": "Standardschläger",
    "itemBlurb.standard-club": "Ein echter Putter, für einen echten Matrosen.",
    "item.golden-club": "Goldener Schläger",
    "itemBlurb.golden-club": "Schwerer, als Gold es sein dürfte.",
    "item.ruby-club": "Rubinschläger",
    "itemBlurb.ruby-club": "Mit einem Stein, nach dem niemand zweimal fragt.",
    "item.master-club": "Meisterschläger",
    "itemBlurb.master-club": "Getragen von Leuten, die es nicht mehr beweisen müssen.",
    "item.pirate-cutlass": "Piratensäbel",
    "itemBlurb.pirate-cutlass": "Kein Golfschläger. Sagen wird es dir aber keiner.",
    "item.flag-club": "Fahnenschläger",
    "itemBlurb.flag-club": "Drei in einer Runde. Sie haben die Fahne für dich gezogen.",
    "item.mechanical-club": "Mechanischer Schläger",
    "itemBlurb.mechanical-club": "Klickt beim Ausrichten. Sally weiß genau, warum.",
    "item.seaside-club": "Strandschläger",
    "itemBlurb.seaside-club": "Zehn Muscheln vom Strand, persönlich übergeben.",
    "item.neon-club": "Neonschläger",
    "itemBlurb.neon-club": "Beleuchtet wie die Promenade am Samstag.",
    "item.stone-ball": "Steinball",
    "itemBlurb.stone-ball": "Rollt. Gerade so.",
    "item.standard-ball": "Standardball",
    "itemBlurb.standard-ball": "Der erste echte Ball, den du besitzen wirst.",
    "item.golden-ball": "Goldener Ball",
    "itemBlurb.golden-ball": "Nicht der geringste Vorteil. Aber alle sehen ihn.",
    "item.ruby-ball": "Rubinball",
    "itemBlurb.ruby-ball": "Fängt das Licht, wenn er an der Fahne vorbeirollt.",
    "item.master-ball": "Meisterball",
    "itemBlurb.master-ball": "Dreißig Stufen Nicht-Aufgeben.",
    "item.crown-ball": "Kronenball",
    "itemBlurb.crown-ball": "Es gibt einen Rang über Kapitän, und du hast ihn.",
    "item.8-ball": "8er-Ball",
    "itemBlurb.8-ball": "Acht auf jedem Loch. Mit Absicht.",
    "item.cannon-ball": "Kanonenkugel",
    "itemBlurb.cannon-ball": "Auf allen neun die Schläge alle. Auch eine Art Rekord.",
    "item.coconut-ball": "Kokosball",
    "itemBlurb.coconut-ball": "Von einer der Palmen. Die Schale ist noch dran.",
    "item.neon-ball": "Neonball",
    "itemBlurb.neon-ball": "Den verlierst du nach Einbruch der Dunkelheit nicht.",
    // ---- odds and ends -----------------------------------------------
    "board.levelShort": "St {n}",
    // ---- the callouts the game raises for itself --------------------
    "toast.welcome.title": "Pirate Mini Golf",
    "toast.welcome.detail": "Schlag ein paar Bälle auf dem Übungsgrün. Trag dich an der Tafel ein, wenn du soweit bist.",
    "toast.tenthShut.title": "Das zehnte ist zu",
    "toast.tenthShut.detail": "Stufe {n} öffnet es. Salt weiß mehr, als er zugibt.",
    "toast.holeTitle": "Loch {n} — {name}",
    "toast.holeDetail": "Par {par}. {hint}",
    "toast.holeWithOne": "Par {par}. Du spielst mit {n} anderen.",
    "toast.holeWithOthers": "Par {par}. Du spielst mit {n} anderen.",
    "toast.roundLeft.title": "Runde verlassen",
    "toast.roundLeft.detail": "Karte zerrissen, nichts gewertet. An der Tafel beim ersten Abschlag kannst du dich neu eintragen.",
    "toast.cardCleared.title": "Karte gelöscht",
    "toast.cardCleared.detail": "Jedes Loch wieder ungespielt.",
    "toast.detectorOut": "Detektor draußen",
    "toast.detectorAway": "Detektor weggepackt",
    "toast.sweepSlowly": "Geh langsam.",
    "toast.clubOut": "Schläger draußen",
    "toast.clubAway": "Schläger weggepackt",
    "toast.scrap.title": "Schrott",
    "toast.scrap.detail": "Etwas aus Metall, und älter als du.",
    "toast.cancelled.title": "Schwung abgebrochen",
    "toast.cancelled.detail": "Kein Schlag gezählt. Richte dich neu aus.",
    "toast.lostBall.title": "Ball verloren",
    "toast.lostBall.detail": "+{n} Schlag. Weiter von dort, wo sie zuletzt lag.",
    "toast.ballReset.title": "Ball zurückgesetzt",
    "toast.ballReset.penalty": "Zurück zur letzten Lage, +{n} Schlag.",
    "toast.ballReset.free": "Zurück zur letzten Lage, ohne Strafe.",
    "toast.pickedUp.title": "Aufgenommen",
    "toast.pickedUp.detail": "Höchstens {n} Schläge auf {hole}.",
    "toast.inOne": "Mit einem",
    "toast.holedSecret": "Du hast das geheime versenkt",
    "toast.holed": "Versenkt",
    "toast.secretOne": "{n} Schlag. Das sehen sehr wenige.",
    "toast.secretMany": "{n} Schläge. Das sehen sehr wenige.",
    "toast.practiceOne": "{n} Schlag. Damit sind es {total} auf dem Übungsgrün.",
    "toast.practiceMany": "{n} Schläge. Damit sind es {total} auf dem Übungsgrün.",
    "score.holeInOne": "HOLE-IN-ONE!",
    "score.eagle": "EAGLE",
    "score.birdie": "BIRDIE",
    "score.par": "PAR",
    "score.bogey": "BOGEY",
    "score.doubleBogey": "DOPPEL-BOGEY",
    "score.over": "+{n}",
    "toast.holeResultOne": "{n} Schlag auf Loch {hole}. Du liegst {standing}.",
    "toast.holeResultMany": "{n} Schläge auf Loch {hole}. Du liegst {standing}.",
    "toast.roundDone.title": "Runde beendet",
    "toast.roundDone.detail": "{total} Schläge für die neun, {label} bei einem Par von {par}.{place} Noch mal.",
    "toast.beat": "  {n} von {of} geschlagen.",
    "toast.cardIn.title": "Karte abgegeben",
    "par.level": "auf Par",
    "par.over": "{n} über",
    "par.under": "{n} unter",
    // ---- what somebody says when they take something off you ----------
    "hand.shellsOne": "{n} Muschel genommen",
    "hand.shellsMany": "{n} Muscheln genommen",
    "hand.coconutsOne": "{n} Kokosnuss genommen",
    "hand.coconutsMany": "{n} Kokosnüsse genommen",
    "hand.paid": "+{n} {pp}",
    "hand.noWallet": "Wallet verbinden, um dafür bezahlt zu werden",
    "hand.noMoreToday": "Heute nimmt er keine mehr",
    "hand.leftInHand": "Noch {n} in der Hand. Er nimmt {limit} am Tag.",
    "hand.forJug": "{n} für den Krug",
    "hand.thatIsTheJug": "Das ist der Krug",
    "hand.jugWanted": "Noch {n} gewünscht.",
    "hand.jugWantedPaid": "Noch {n} gewünscht.  +{paid} {pp}",
    "hand.goTellHim": "Geh und sag es ihm.",
    "hand.motor.title": "Der alte Motor",
    "hand.motor.detail": "Schwerer, als er aussieht. Coconutty wird das sehen wollen.",
    "hand.scrapOne": "{n} Schrott abgegeben",
    "hand.scrapMany": "{n} Schrott abgegeben",
    "hand.scrapDetail": "{total} insgesamt. Sie sortiert schon, während du gehst.",
    "hand.detectorOut": "Detektor draußen",
    "hand.detectorAway": "Detektor weggepackt",
    "hand.sweepSlowly": "Geh langsam und lass ihn klicken.",
    "hand.notThisTime": "Diesmal nicht"
  },
  fr: {
    // ---- the strip along the top -------------------------------------------
    "hud.practice": "ENTRAÎN.",
    "hud.secret": "SECRET",
    "hud.shot": "Coup {n}",
    "hud.shotOf": "Coup {n} sur {max}  ·  {dist}",
    "hud.holed": "{n} rentrées  ·  coup {shot}",
    "hud.toJoin": "jouer",
    "hud.toJoinKey": "E  jouer",
    "hud.boardAway": "Tableau {dist}",
    "hud.par": "PAR {n}",
    // ---- the scorecard and the standings -----------------------------------
    "hud.total": "TOT",
    "hud.parLine": "Par {par}    {toPar}",
    "hud.playing": "EN JEU  {n}",
    "hud.roundComplete": "PARTIE TERMINÉE    {total}  ({toPar})",
    "hud.playAgain": "pour rejouer le parcours",
    "hud.playAgainKey": "Appuie sur E pour rejouer le parcours",
    // ---- the chips ---------------------------------------------------------
    "hud.colada": "COLADA",
    "hud.dig": "CREUSER",
    "hud.digKey": "CREUSER  (E)",
    "hud.sweeping": "RECHERCHE",
    "hud.nothingFound": "RIEN",
    // ---- what to press -----------------------------------------------------
    "prompt.walkToBall": "Approche-toi de ta balle",
    "prompt.address": "{E}  pour te placer",
    "prompt.addressKey": "Appuie sur  E  pour te placer",
    "prompt.aim": "Vise où tu veux l’envoyer,  puis  {E}",
    "prompt.aimKey": "Vise où tu veux l’envoyer,  puis  E",
    // ---- the swing meter ---------------------------------------------------
    "meter.setPower": "RÈGLE LA FORCE",
    "meter.hitLine": "VISE LA LIGNE",
    "meter.lockPower": "pour bloquer la force",
    "meter.lockPowerKey": "Appuie sur  E  pour bloquer la force",
    "meter.onLine": "sur la ligne blanche",
    "meter.onLineAgain": "encore sur la ligne blanche",
    "meter.onLineKey": "Appuie sur  E  sur la ligne blanche",
    "meter.crossCancels": "la croix annule",
    "meter.crossCancelsShort": "la croix annule",
    "meter.fCancels": "F  annuler",
    // ---- the hub -----------------------------------------------------------
    "hub.title": "SAC",
    "hub.reset": "REPLACER",
    "hub.leave": "QUITTER",
    "hub.sure": "SÛR ?",
    "hub.close": "X",
    "hub.quests": "QUÊTES",
    "hub.gear": "MATÉRIEL",
    "hub.stash": "BUTIN",
    "hub.settings": "RÉGLAGES",
    "hub.active": "EN COURS",
    "hub.available": "DISPOS",
    "hub.completed": "FINIES",
    "hub.clubs": "CLUBS",
    "hub.balls": "BALLES",
    "hub.gearHint":
      "Touche un club ou une balle que tu as pour la prendre. Salt vend le reste, à la cabane.",
    "hub.stashHint": "Ce que tu transportes. Donne-le à qui le veut.",
    "hub.settingsHint": "Comment le jeu t’apparaît. Personne d’autre.",
    "hub.andMore": "et {n} de plus",
    "hub.nothingActive": "Rien en cours. Va parler à quelqu’un.",
    "hub.nothingAvailable": "Rien à prendre. Finis ce que tu as commencé.",
    "hub.nothingDone": "Rien de fini pour l’instant.",
    "hub.speakTo": "Parle à {who}",
    "hub.readyToHandIn": "Finie. Parle à {who}",
    "hub.reward": "+{n} {pp}",
    "hub.progress": "{done} / {target}",
    // ---- settings ----------------------------------------------------------
    "settings.on": "OUI",
    "settings.off": "NON",
    "settings.hidePrompts": "Masquer les infos",
    "settings.hidePromptsDetail": "Coupe la ligne en bas qui te dit quoi faire.",
    "settings.talkInRounds": "Parler pendant la partie",
    "settings.talkInRoundsDetail":
      "Les personnages peuvent t’arrêter en pleine partie. Jamais pendant un coup.",
    "settings.language": "Langue",
    "settings.languageDetail": "Ce qui n’est pas encore traduit reste en anglais.",
    // ---- the stash ---------------------------------------------------------
    "stash.shells": "Coquillages",
    "stash.shellsDetail": "{who} les veut, en bas sur la plage sud.",
    "stash.coconuts": "Noix de coco",
    "stash.coconutsDetail": "{who} les veut, là-haut près des palmiers.",
    "stash.scrap": "Ferraille",
    "stash.scrapDetail": "Déterrée au détecteur. {who} en a besoin.",
    "stash.limitReached": "{n}  ·  plus rien aujourd’hui",
    // ---- the crate and the gear rows ---------------------------------------
    "shop.equipped": "EN MAIN",
    "shop.equip": "PRENDRE",
    "shop.atSalt": "{price}  ·  SALT",
    "shop.questReward": "Récompense",
    "shop.questLocked": "Quête : {name}",
    "shop.walkAway": "Éloigne-toi pour fermer",
    "shop.needLevel": "Niveau {n}",
    // ---- levelling ---------------------------------------------------------
    "level.title": "NIVEAU {n}",
    "level.titleGained": "NIVEAU {n}  (+{gained})",
    "level.onTheShelf": "{rank}  ·  {n} en rayon",
    "level.connectWallet": "Connecte un portefeuille pour être payé",
    // ---- the four lines every quest conversation uses ----------------------
    "quest.take": "Je la prends",
    "quest.notNow": "Pas maintenant",
    "quest.collect": "Toucher {n} {pp}",
    "quest.inAMinute": "Dans un instant",
    "quest.rightYouAre": "Très bien",
    // ---- the sign-up board out on the decking ------------------------------
    "sign.title": "PIRATE MINI GOLF",
    "sign.join": "Rejoins la partie",
    "sign.toJoin": "pour rejoindre",
    "sign.toJoinKey": "Appuie sur E pour rejoindre",
    "sign.playing": "{n} en jeu",
    "sign.watching": "{n} à côté",
    "sign.youAreIn": "Tu es inscrit. Va au départ.",
    // ---- the leaderboard sign ----------------------------------------------
    "board.waiting": "En attente du registre…",
    "board.nobody": "Personne encore. Sois le premier.",
    // ---- the quest sign ----------------------------------------------------
    "questboard.title": "QUÊTES",
    "questboard.nothing": "Rien en cours. Renseigne-toi.",
    "questboard.readyToHandIn": "Finie. Parle à {who}",
    // ---- the ranks, keyed off the English name in ranks.ts -----------------
    "rank.cabin-boy": "Mousse",
    "rank.deckhand": "Matelot",
    "rank.buccaneer": "Boucanier",
    "rank.first-mate": "Second",
    "rank.captain": "Capitaine",
    "rank.pirate-lord": "Grand Pirate",
    // ---- the holes, keyed off the English name in course.ts ----------------
    "hole.the-jetty": "La Jetée",
    "hole.anchors-rest": "Repos de l’Ancre",
    "hole.triple-bridge": "Triple Pont",
    "hole.the-blockade": "Le Blocus",
    "hole.barrel-run": "Course au Tonneau",
    "hole.the-lighthouse": "Le Phare",
    "hole.ships-passing": "Passage du Navire",
    "hole.dead-mans-arch": "Arche du Mort",
    "hole.treasure-run": "Course au Trésor",
    "hole.the-secret-hole": "Le Trou Secret",
    // ---- what each hole asks of you ----------------------------------------
    "holeHint.the-jetty": "Un léger dog-leg. Joue-la sur la bande.",
    "holeHint.anchors-rest": "Monte la rampe, passe l’ancre. Mets-y du poids.",
    "holeHint.triple-bridge": "Descends la pente, puis passe entre les trous.",
    "holeHint.the-blockade": "Deux fossés ouverts entre toi et le drapeau.",
    "holeHint.barrel-run": "Choisis ton moment, puis reste au sec.",
    "holeHint.the-lighthouse": "Contourne le phare, puis monte sur le pont.",
    "holeHint.ships-passing": "Le galion te fait traverser. Attends ton passage.",
    "holeHint.dead-mans-arch": "Deux grosses bosses. Frappe ferme ou la pente la renvoie.",
    "holeHint.treasure-run": "Toute l’île, deux ponts suspendus, et un coffre au bout.",
    "holeHint.the-secret-hole": "Personne n’est obligé. Vingt coups, puis il te reprend la balle.",
    "holeHint.practice": "Échauffement. Rentre-la et la balle revient.",
    // ---- the leaderboard sign, keyed off its page keys in config -----
    "board.levelHeading": "MEILLEURS RANGS",
    "board.levelNote": "Par Pixel Points cumulés",
    "board.bestHeading": "MEILLEURES PARTIES",
    "board.bestNote": "Moins de coups sur les neuf",
    "board.todayHeading": "AUJOURD'HUI",
    "board.todayNote": "Pixel Points gagnés aujourd’hui",
    // ---- the shop catalogue, keyed off the English name in shop.ts ---
    "item.stick-club": "Club en Bâton",
    "itemBlurb.stick-club": "Un bâton. Tu l’as trouvé en arrivant.",
    "item.standard-club": "Club Standard",
    "itemBlurb.standard-club": "Un vrai putter, pour un vrai matelot.",
    "item.golden-club": "Club Doré",
    "itemBlurb.golden-club": "Plus lourd que l’or n’a le droit de l’être.",
    "item.ruby-club": "Club Rubis",
    "itemBlurb.ruby-club": "Serti d’une pierre sur laquelle on ne revient pas.",
    "item.master-club": "Club de Maître",
    "itemBlurb.master-club": "Porté par ceux qui n’ont plus rien à prouver.",
    "item.pirate-cutlass": "Sabre de Pirate",
    "itemBlurb.pirate-cutlass": "Ce n’est pas un club de golf. Personne ne te le dira.",
    "item.flag-club": "Club au Drapeau",
    "itemBlurb.flag-club": "Trois dans une partie. Ils ont retiré le drapeau pour toi.",
    "item.mechanical-club": "Club Mécanique",
    "itemBlurb.mechanical-club": "Il clique à l’alignement. Sally sait pourquoi.",
    "item.seaside-club": "Club du Bord de Mer",
    "itemBlurb.seaside-club": "Dix coquillages de la plage, remis en main propre.",
    "item.neon-club": "Club Néon",
    "itemBlurb.neon-club": "Illuminé comme la jetée un samedi soir.",
    "item.stone-ball": "Balle de Pierre",
    "itemBlurb.stone-ball": "Elle roule. À peine.",
    "item.standard-ball": "Balle Standard",
    "itemBlurb.standard-ball": "La première vraie balle que tu posséderas.",
    "item.golden-ball": "Balle Dorée",
    "itemBlurb.golden-ball": "Aucun avantage. Mais tout le monde la voit.",
    "item.ruby-ball": "Balle Rubis",
    "itemBlurb.ruby-ball": "Elle accroche la lumière en passant le drapeau.",
    "item.master-ball": "Balle de Maître",
    "itemBlurb.master-ball": "Trente niveaux à ne pas abandonner.",
    "item.crown-ball": "Balle Couronne",
    "itemBlurb.crown-ball": "Il y a un rang au-dessus de Capitaine, et il est à toi.",
    "item.8-ball": "Balle 8",
    "itemBlurb.8-ball": "Huit à chaque trou. Volontairement.",
    "item.cannon-ball": "Boulet de Canon",
    "itemBlurb.cannon-ball": "Coups épuisés sur les neuf. Une sorte de record.",
    "item.coconut-ball": "Balle de Coco",
    "itemBlurb.coconut-ball": "Tombée d’un des palmiers. Elle a encore sa bourre.",
    "item.neon-ball": "Balle Néon",
    "itemBlurb.neon-ball": "Tu ne la perdras pas une fois la nuit tombée.",
    // ---- odds and ends -----------------------------------------------
    "board.levelShort": "Nv {n}",
    // ---- the callouts the game raises for itself --------------------
    "toast.welcome.title": "Pirate Mini Golf",
    "toast.welcome.detail": "Tape quelques balles sur le green d’entraînement. Inscris-toi au panneau quand tu es prêt.",
    "toast.tenthShut.title": "Le dixième est fermé",
    "toast.tenthShut.detail": "Le niveau {n} l’ouvre. Salt en sait plus qu’il ne le dit.",
    "toast.holeTitle": "Trou {n} — {name}",
    "toast.holeDetail": "Par {par}. {hint}",
    "toast.holeWithOne": "Par {par}. Tu joues avec {n} autre.",
    "toast.holeWithOthers": "Par {par}. Tu joues avec {n} autres.",
    "toast.roundLeft.title": "Partie quittée",
    "toast.roundLeft.detail": "Carte déchirée, rien de marqué. Le panneau du premier départ te réinscrit.",
    "toast.cardCleared.title": "Carte effacée",
    "toast.cardCleared.detail": "Chaque trou revient à non joué.",
    "toast.detectorOut": "Détecteur sorti",
    "toast.detectorAway": "Détecteur rangé",
    "toast.sweepSlowly": "Balaie lentement.",
    "toast.clubOut": "Club sorti",
    "toast.clubAway": "Club rangé",
    "toast.scrap.title": "Ferraille",
    "toast.scrap.detail": "Quelque chose en métal, et plus vieux que toi.",
    "toast.cancelled.title": "Swing annulé",
    "toast.cancelled.detail": "Aucun coup compté. Replace-toi.",
    "toast.lostBall.title": "Balle perdue",
    "toast.lostBall.detail": "+{n} coup. On rejoue d’où elle s’était arrêtée.",
    "toast.ballReset.title": "Balle replacée",
    "toast.ballReset.penalty": "Retour à ta dernière position, +{n} coup.",
    "toast.ballReset.free": "Retour à ta dernière position, sans pénalité.",
    "toast.pickedUp.title": "Ramassée",
    "toast.pickedUp.detail": "Maximum {n} coups sur {hole}.",
    "toast.inOne": "En un coup",
    "toast.holedSecret": "Tu as rentré le secret",
    "toast.holed": "Rentrée",
    "toast.secretOne": "{n} coup. Très peu de gens voient ça.",
    "toast.secretMany": "{n} coups. Très peu de gens voient ça.",
    "toast.practiceOne": "{n} coup. Ça fait {total} sur le green d’entraînement.",
    "toast.practiceMany": "{n} coups. Ça fait {total} sur le green d’entraînement.",
    "score.holeInOne": "TROU EN UN !",
    "score.eagle": "EAGLE",
    "score.birdie": "BIRDIE",
    "score.par": "PAR",
    "score.bogey": "BOGEY",
    "score.doubleBogey": "DOUBLE BOGEY",
    "score.over": "+{n}",
    "toast.holeResultOne": "{n} coup au trou {hole}. Tu es {standing}.",
    "toast.holeResultMany": "{n} coups au trou {hole}. Tu es {standing}.",
    "toast.roundDone.title": "Partie terminée",
    "toast.roundDone.detail": "{total} coups pour les neuf, {label} pour un par de {par}.{place} On recommence.",
    "toast.beat": "  Tu as battu {n} sur {of}.",
    "toast.cardIn.title": "Carte rendue",
    "par.level": "dans le par",
    "par.over": "{n} au-dessus",
    "par.under": "{n} en dessous",
    // ---- what somebody says when they take something off you ----------
    "hand.shellsOne": "{n} coquillage pris",
    "hand.shellsMany": "{n} coquillages pris",
    "hand.coconutsOne": "{n} noix de coco prise",
    "hand.coconutsMany": "{n} noix de coco prises",
    "hand.paid": "+{n} {pp}",
    "hand.noWallet": "Connecte un portefeuille pour être payé",
    "hand.noMoreToday": "Il n’en prendra plus aujourd’hui",
    "hand.leftInHand": "Il t’en reste {n}. Il en prend {limit} par jour.",
    "hand.forJug": "{n} pour le pichet",
    "hand.thatIsTheJug": "Voilà le pichet",
    "hand.jugWanted": "Il en faut {n} de plus.",
    "hand.jugWantedPaid": "Il en faut {n} de plus.  +{paid} {pp}",
    "hand.goTellHim": "Va le lui dire.",
    "hand.motor.title": "Le vieux moteur",
    "hand.motor.detail": "Plus lourd qu’il n’en a l’air. Coconutty voudra voir ça.",
    "hand.scrapOne": "{n} ferraille remise",
    "hand.scrapMany": "{n} ferrailles remises",
    "hand.scrapDetail": "{total} en tout. Elle trie déjà pendant que tu pars.",
    "hand.detectorOut": "Détecteur sorti",
    "hand.detectorAway": "Détecteur rangé",
    "hand.sweepSlowly": "Balaie lentement et laisse-le cliquer.",
    "hand.notThisTime": "Pas cette fois"
  }
}
