// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Anchor_glb = "Anchor.glb",
  Back_glb_2 = "Back.glb_2",
  Back_glb_3 = "Back.glb_3",
  Barrel_glb = "Barrel.glb",
  Barrels_and_Crates_glb = "Barrels and Crates.glb",
  Blender_glb = "Blender.glb",
  Cannonballs_glb = "Cannonballs.glb",
  Cannons_glb = "Cannons.glb",
  Cave_glb = "Cave.glb",
  Coins_Scattered_glb = "Coins Scattered.glb",
  Decking_glb = "Decking.glb",
  Door_Frame_glb = "Door Frame.glb",
  Environ = "Environ",
  Floor_Guide_UI_glb = "Floor Guide UI.glb",
  Hole_1_Base_glb = "Hole 1 Base.glb",
  Hole_1_Flag_Pole_glb = "Hole 1 Flag Pole.glb",
  Hole_1_Trim_glb = "Hole 1 Trim.glb",
  Hole_2_Base_glb = "Hole 2 Base.glb",
  Hole_2_Flag_glb = "Hole 2 Flag.glb",
  Hole_2_Trim_glb = "Hole 2 Trim.glb",
  Hole_3_Base_glb = "Hole 3 Base.glb",
  Hole_3_Flag_glb = "Hole 3 Flag.glb",
  Hole_3_Trim_glb = "Hole 3 Trim.glb",
  Hole_4_Base_glb = "Hole 4 Base.glb",
  Hole_4_Flag_glb = "Hole 4 Flag.glb",
  Hole_4_Trim_glb = "Hole 4 Trim.glb",
  Hole_5_Base_glb = "Hole 5 Base.glb",
  Hole_5_Flag_glb = "Hole 5 Flag.glb",
  Hole_5_Trim_glb = "Hole 5 Trim.glb",
  Hole_6_Base_glb = "Hole 6 Base.glb",
  Hole_6_Flag_glb = "Hole 6 Flag.glb",
  Hole_6_Trim_glb = "Hole 6 Trim.glb",
  Hole_7_Base_glb = "Hole 7 Base.glb",
  Hole_7_Flag_glb = "Hole 7 Flag.glb",
  Hole_7_Trim_glb = "Hole 7 Trim.glb",
  Hole_8_Base_glb = "Hole 8 Base.glb",
  Hole_8_Flag_glb = "Hole 8 Flag.glb",
  Hole_8_Trim_glb = "Hole 8 Trim.glb",
  Hole_9_Base_glb = "Hole 9 Base.glb",
  Hole_9_Flags_glb = "Hole 9 Flags.glb",
  Hole_9_Trim_glb = "Hole 9 Trim.glb",
  Islands_glb = "Islands.glb",
  LeaderBoard = "LeaderBoard",
  Left_Door_glb = "Left Door.glb",
  Lighthouse_glb = "Lighthouse.glb",
  Lights_glb = "Lights.glb",
  Moving_Ramp_glb = "Moving Ramp.glb",
  Ocean_V2_glb = "Ocean V2.glb",
  Palm_Trees_glb = "Palm Trees.glb",
  Pina_Colada_glb = "Pina Colada.glb",
  Practice_Hole_Base_glb = "Practice Hole Base.glb",
  Practice_Hole_Trim_glb = "Practice Hole Trim.glb",
  Quests = "Quests",
  Right_Door_glb = "Right Door.glb",
  Rocks_glb = "Rocks.glb",
  Sand_Plane_glb = "Sand Plane.glb",
  Seagull_glb = "Seagull.glb",
  Secret_Hole_Base_glb = "Secret Hole Base.glb",
  Secret_Hole_Flag_glb = "Secret Hole Flag.glb",
  Secret_Hole_Trim_glb = "Secret Hole Trim.glb",
  Shack_glb = "Shack.glb",
  Skeletons_glb = "Skeletons.glb",
  Table_glb = "Table.glb",
  Treasure_Chest_glb = "Treasure Chest.glb",
  Tutorial_Desktop_glb = "Tutorial Desktop.glb",
  Tutorial_Mobile_glb = "Tutorial Mobile.glb",
  Vertical_Waterfall_glb = "Vertical Waterfall.glb",
  Vertical_Waterfall_glb_2 = "Vertical Waterfall.glb_2",
  Wheel_glb = "Wheel.glb",
  ball = "ball",
  boat_glb = "boat.glb",
  logo_glb = "logo.glb",
} 
