// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Anchor_glb = "Anchor.glb",
  Balls_glb = "Balls.glb",
  Barrel_glb = "Barrel.glb",
  Clubs_glb = "Clubs.glb",
  Decking_glb = "Decking.glb",
  Environ = "Environ",
  Hole_1_Base_glb = "Hole 1 Base.glb",
  Hole_1_Flag_Pole_glb = "Hole 1 Flag Pole.glb",
  Hole_1_Trim_glb = "Hole 1 Trim.glb",
  Hole_2_Base_glb = "Hole 2 Base.glb",
  Hole_2_Flag_glb = "Hole 2 Flag.glb",
  Hole_2_Trim_glb = "Hole 2 Trim.glb",
  Hole_3_Base_glb = "Hole 3 Base.glb",
  Hole_3_Flag_glb = "Hole 3 Flag.glb",
  Hole_3_Trim_glb = "Hole 3 Trim.glb",
  Hole_4_Base_glb = "Hole 4 Base.glb",
  Hole_4_Flag_glb = "Hole 4 Flag.glb",
  Hole_4_Trim_glb = "Hole 4 Trim.glb",
  Hole_5_Base_glb = "Hole 5 Base.glb",
  Hole_5_Flag_glb = "Hole 5 Flag.glb",
  Hole_5_Trim_glb = "Hole 5 Trim.glb",
  Hole_6_Base_glb = "Hole 6 Base.glb",
  Hole_6_Flag_glb = "Hole 6 Flag.glb",
  Hole_6_Trim_glb = "Hole 6 Trim.glb",
  Hole_7_Base_glb = "Hole 7 Base.glb",
  Hole_7_Flag_glb = "Hole 7 Flag.glb",
  Hole_7_Trim_glb = "Hole 7 Trim.glb",
  Hole_8_Base_glb = "Hole 8 Base.glb",
  Hole_8_Flag_glb = "Hole 8 Flag.glb",
  Hole_8_Trim_glb = "Hole 8 Trim.glb",
  Hole_9_Base_glb = "Hole 9 Base.glb",
  Hole_9_Flags_glb = "Hole 9 Flags.glb",
  Hole_9_Trim_glb = "Hole 9 Trim.glb",
  Islands_glb = "Islands.glb",
  Lighthouse_glb = "Lighthouse.glb",
  Lights_glb = "Lights.glb",
  Moving_Ramp_glb = "Moving Ramp.glb",
  Ocean_V2_glb = "Ocean V2.glb",
  Palm_Trees_glb = "Palm Trees.glb",
  Practice_Hole_Base_glb = "Practice Hole Base.glb",
  Practice_Hole_Trim_glb = "Practice Hole Trim.glb",
  Rocks_glb = "Rocks.glb",
  Sand_Plane_glb = "Sand Plane.glb",
  Secret_Hole_Base_glb = "Secret Hole Base.glb",
  Secret_Hole_Flag_glb = "Secret Hole Flag.glb",
  Secret_Hole_Trim_glb = "Secret Hole Trim.glb",
  Shack_glb = "Shack.glb",
  Treasure_Chest_glb = "Treasure Chest.glb",
  Wheel_glb = "Wheel.glb",
  ball = "ball",
  boat_glb = "boat.glb",
} 
